ultraio/docs-blockchain

README.md, docs/.vitepress/theme/index.ts, docs/layout/environments/Experimental.vue, docs/layout/environments/Mainnet.vue, docs/layout/environments/Staging.vue, packages/mainnet/docs/.vitepress/theme/index.ts, packages/staging/docs/.vitepress/theme/index.ts
Allows support of rendering specific content for specific environments only.
=> BLOCK-1544 - Environment Sections

docs/contracts/NFT Contract/NFT Actions/setsharelim.md, docs/contracts/NFT Contract/nft-tables.md
[BLOCK-1463](https://ultraio.atlassian.net/browse/BLOCK-1463)
Adds table and action documentation for share limit adjustment action
[BLOCK-1463]: https://ultraio.atlassian.net/browse/BLOCK-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BLOCK-1463] - Added documentation for new max sale share tweaking action

docs/contracts/NFT Contract/NFT Actions/adjtrdwin.a.md, docs/contracts/NFT Contract/NFT Actions/settrdwin.a.md
[BLOCK-1485](https://ultraio.atlassian.net/browse/BLOCK-1485)
[BLOCK-1485]: https://ultraio.atlassian.net/browse/BLOCK-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BLOCK-1485 add documentation for settrdwin.a action

docs/contracts/NFT Contract/NFT Actions/settrnfwin.a.md
[BLOCK-1486](https://ultraio.atlassian.net/browse/BLOCK-1486)
Added docs for `settrnfwin.a`. 
[BLOCK-1486]: https://ultraio.atlassian.net/browse/BLOCK-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BLOCK-1486 add documentation for settrnfwin.a action

docs/contracts/NFT Contract/NFT Actions/setprchsreq.md
Code PR: https://github.com/ultraio/eosio.contracts/pull/477
=> BLOCK-1472 - Set up USD price for factory

docs/contracts/NFT Contract/NFT Actions/setsharelim.md, docs/contracts/NFT Contract/NFT Actions/settrdwin.a.md, docs/contracts/NFT Contract/NFT Actions/settrnfwin.a.md, docs/contracts/NFT Contract/nft-tables.md
Added actions related to fee tweaking and transfer/trading window changes to Testnet/Mainnet
=> Promote window changes and fee tweaking

docs/learn/Ultra Blockchain/power-resource.md
fix the broken link to rate limit doc in power doc
=> BLOCK-1819-fix-borken-link-to-trx-queue

docs/contracts/NFT Contract/NFT Actions/setprchsreq.a.md
Add more concrete examples for the group_restriction action parameter
=> BLOCK-1896-add more examples for group_restriction parameter

docs/contracts/User Group Contract/User Group Actions/adduser.md, docs/contracts/User Group Contract/User Group Actions/clear.md, docs/contracts/User Group Contract/User Group Actions/create.md, docs/contracts/User Group Contract/User Group Actions/rmuser.md, docs/contracts/User Group Contract/User Group Actions/setmeta.md, docs/contracts/User Group Contract/overview.md, docs/contracts/User Group Contract/user-group-tables.md
Hi @Adam-Ultra ,
Could you please review user group deployment ticket?
Thanks,
Janos
=> [BLOCK-1846] - deploy user group contract on testnet

docs/guides/Wallet Extension/custom-networks.md, docs/guides/Wallet Extension/demo-application.md, docs/guides/Wallet Extension/detect-blockchain-network.md, docs/guides/Wallet Extension/developer-resources.md, docs/guides/Wallet Extension/errors.md, docs/guides/Wallet Extension/establishing-connection.md, docs/guides/Wallet Extension/events.md, docs/guides/Wallet Extension/get-tokens-testnet.md, docs/guides/Wallet Extension/import-private_key.md, docs/guides/Wallet Extension/signing-transaction.md, docs/guides/Wallet Extension/signing_message.md
Create a documentation section for the Ultra Wallet Extension method `window.ultra.getChainId()`
=> task/GP-21882: uwax method to get chain id

docs/contracts/User Group Contract/User Group Actions/adduser.md, docs/contracts/User Group Contract/User Group Actions/clear.md, docs/contracts/User Group Contract/User Group Actions/create.md, docs/contracts/User Group Contract/User Group Actions/rmuser.md, docs/contracts/User Group Contract/User Group Actions/setmeta.md, docs/contracts/User Group Contract/overview.md, docs/contracts/User Group Contract/user-group-tables.md
Hi @Adam-Ultra ,
Could you please review this ticket?
Thanks
=> [BLOCK-1847] - deploy user group contract on mainnet

docs/contracts/NFT Contract/NFT Actions/settrdwin.a.md, docs/contracts/NFT Contract/NFT Actions/settrnfwin.a.md, docs/guides/Uniq Factory Management/exchange-a-uniq-using-smart-contract.md, docs/guides/Uniq Factory Management/factory-purchase-options-examples.md, docs/guides/Uniq Factory Management/factory-purchase-options.md
Adds new section to guides `Uniq Factory Management` and describes the usage of first-hand purchase feature and example smart contract to be able to swap Uniqs
=> [BLOCK-1952] - Purchase option use cases

.gitignore, docs/.vitepress/sidebars/base.ts, docs/blockchain/contracts/nft-contract/nft-actions/issue.b.md, docs/blockchain/contracts/nft-contract/nft-actions/setprchsreq.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/setprchsreq.a.mainnet.md, docs/blockchain/contracts/nft-contract/nft-actions/setprchsreq.a.staging.md, docs/blockchain/contracts/nft-contract/nft-actions/setprchsreq.b.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/setprchsreq.b.staging.md, docs/tutorials/uniq-factories/factory-management/uniq-first-hand-purchase-example-project.md, docs/tutorials/uniq-factories/factory-management/uniq-swap-example-project.md
- Renames Token Swap section name to properly reflect that
- Updates types for `issue.b` action, updates the action usage examples
- Adds a page referencing the usage and explanation of example first hand purchase page
=> [BLOCK-1965] - Added a page for first hand purchase example project

docs/.vitepress/sidebars/base.ts, docs/blockchain/block-producers/launch-procedures/registering-block-producers.md, docs/blockchain/block-producers/launch-procedures/setting-up-genesis-node.md, docs/blockchain/contracts/oracle-contract/how-does-oracle-contract-calculate-uos-conversion-rate.md, docs/blockchain/contracts/oracle-contract/index.md, docs/blockchain/contracts/oracle-contract/oracle-actions/addma.md, docs/blockchain/contracts/oracle-contract/oracle-actions/calcsecma.md, docs/blockchain/contracts/oracle-contract/oracle-actions/init.md, docs/blockchain/contracts/oracle-contract/oracle-actions/purgefrates.md, docs/blockchain/contracts/oracle-contract/oracle-actions/pushrate.md, docs/blockchain/contracts/oracle-contract/oracle-actions/regexchange.md, docs/blockchain/contracts/oracle-contract/oracle-actions/removema.md, docs/blockchain/contracts/oracle-contract/oracle-actions/resetfavg.md, docs/blockchain/contracts/oracle-contract/oracle-actions/resetfeed.md, docs/blockchain/contracts/oracle-contract/oracle-actions/resetfrates.md, docs/blockchain/contracts/oracle-contract/oracle-actions/terminate.md, docs/blockchain/contracts/oracle-contract/oracle-actions/unregexchg.md, docs/blockchain/contracts/oracle-contract/oracle-tables.md, docs/tutorials/oracle/how-to-get-uos-conversion-rate.md, docs/tutorials/oracle/how-to-validate-and-refresh-moving-average.md, docs/tutorials/smart-contracts/deploy.md
- Adds missing documentation for oracle contract actions and how to interact with the contract
- Updates the small issue in the account creation command for smart contract deployment
=> [BLOCK-1547] - Added oracle documentation

docs/products/ultra-wallet/detect-wallet.md
adding a code to explain how use it in the DOM load event.
=> Update detect-wallet to add explanation on DOM load event use

docs/blockchain/general/antelope-ultra/public-and-private-keys.md, docs/products/ultra-wallet/detect-wallet.md
- fix broken link 
-  minor fix on detect-wallet.md
=> fix broken link + minor fix on detect-wallet.md

.github/workflows/build.yml, docs/tutorials/fundamentals/how-to-setup-the-wallet.md
- added workflow for build generation on PR
- minor fix broken link
=> added workflow for build generation on PR + minor fix broken link

docs/blockchain/general/tools/cleos.md
=> Update Staging to Testnet

docs/products/chain-api/index.md
=> Update test networking

docs/components/CustomLayout.vue
Update staging text to Testnet
=> Update staging text

docs/products/nft-api/authentication.md, docs/products/nft-api/introduction.md, docs/products/nft-api/queries.md, docs/products/nft-api/release.md, docs/products/nft-api/subscriptions.md, docs/products/nft-api/types.md
Update buy offer documentation
=> task/GP-23964/GP-24203 : Update buy offer documentation

docs/tutorials/uniq-factories/creating-uniq-factories/how-to-create-uniq-factory-using-toolkit.md
Reverts ultraio/docs-blockchain#236
=> Revert "Try fix Uniq Tutorial"

docs/.vitepress/sidebars/base.ts, docs/blockchain/contracts/nft-contract/nft-actions/createauct.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/resell.md, docs/blockchain/contracts/nft-contract/nft-actions/stauctcfg.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-tables.experimental.md, docs/tutorials/uniq-factories/uniq-auction/uniq-auction.experimental.md
- Adds documentation for 2 new auction actions
- Update NFT tables page to add new auction-related tables
- Adds scaffold for Auction feature description document
=> BLOCK-2436 - Added auction actions and tables documentation

docs/blockchain/contracts/nft-contract/nft-actions/settleauct.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-tables.experimental.md, docs/blockchain/general/antelope-ultra/2nd-hand-sale.experimental.md, docs/tutorials/uniq-factories/uniq-auction/uniq-auction.experimental.md
- Adds a document for settleauct.a action
- Updates references to auction actions
=> BLCOK-2439 - Settle auction action document

docs/blockchain/contracts/nft-contract/nft-actions/bidauction.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/cancelauct.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/createauct.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-actions/settleauct.a.experimental.md, docs/blockchain/contracts/nft-contract/nft-tables.experimental.md, docs/tutorials/uniq-factories/uniq-auction/uniq-auction.experimental.md
- Adds a document for cancel auction action
- Fixes grammar in existing Uniq auction documents
=> BLOCK-2440 - Cancel auction action

docs/tutorials/uniq-factories/creating-uniq-factories/how-to-create-multiple-uniq-factories-using-toolkit.md
* Added Google Sheet link to access `Bulk Factory Creation - Template`
=> task/GP-24898: add template link to create multiple uniqfact tutorial

docs/public/descriptors/eosio.nft.ft-descriptor.json
- Move the NFT descriptor to be accessible from docs (moved to /docs/public/)
- Add auction actions to the NFT descriptor
=> BLOCK-2443 - Auction actions in tool kit

docs/blockchain/contracts/nft-contract/nft-actions/bidauction.a.experimental.md
=> Update bidauction.a eosjs example

docs/products/ultra-wallet-sdk/core-api-methods.experimental.md
Small adjustment for connect with nonce parameter
=> task/GP-26261: nonce on connect requires user confirmation

docs/.vitepress/navbar.ts, docs/.vitepress/sidebars/base.ts, docs/blockchain/contracts/rng-contract/index.md, docs/blockchain/contracts/rng-contract/rng-actions/ban.md, docs/blockchain/contracts/rng-contract/rng-actions/killjobs.md, docs/blockchain/contracts/rng-contract/rng-actions/requestrand.md, docs/blockchain/contracts/rng-contract/rng-actions/setpubkey.md, docs/blockchain/contracts/rng-contract/rng-actions/setrand.md, docs/blockchain/contracts/rng-contract/rng-actions/unban.md, docs/blockchain/contracts/rng-contract/rng-tables.md, docs/tutorials/index/index.md, docs/tutorials/rng/how-to-integrate-rng-in-smart-contracts.md, scripts/verifyLinks.ts
- Add contract page: include overview, table and actions
- Simple tutorial on how to integrate on-chain RGN in your smart contract.
=> [BLOCK-2641] how to integrate rng in smart contract

docs/.vitepress/config.ts, docs/index.md, docs/tutorials/smart-contracts/troubleshooting.md, docs/tutorials/token-swap/index.md
Update broken discord invites.
=> internal: update discord invite channel
